server.port=8080
# Configuracion de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/ejemplo
spring.datasource.username=*****
spring.datasource.password==*****

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#Permite conocer los endpoints
logging.level.org.springframework.web.servlet.mvc.method.annotation=TRACE
spring.jpa.properties.hibernate.format_sql=true
#
#Instruciones para ddl-auto
#- create: crea las tablas al iniciar la aplicacion, pero no las elimina automaticamente al detenerle
#- create-drop:Crea las tablas al iniciar la aplicacion, pero las elimina al finalizarla.---
#- update: Solo actualiza el esquema existente, agregando o modificando tablas y columnas sin eliminarlas.
#- Validate: Valida que el esquema existente coincida con las entidades de JPA, pero no hace cambios.
#
spring.jpa.hibernate.ddl-auto=update


#springdoc.api-docs.path=/api-docs
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
