package Primero;
// Generated 23-ene-2022 13:04:34 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos implements java.io.Serializable {

	private int idDep;
	private String nombreDep;
	private Set empleadoses = new HashSet(0);

	public Departamentos() {
	}

	public Departamentos(int idDep, String nombreDep) {
		this.idDep = idDep;
		this.nombreDep = nombreDep;
	}

	public Departamentos(int idDep, String nombreDep, Set empleadoses) {
		this.idDep = idDep;
		this.nombreDep = nombreDep;
		this.empleadoses = empleadoses;
	}

	public int getIdDep() {
		return this.idDep;
	}

	public void setIdDep(int idDep) {
		this.idDep = idDep;
	}

	public String getNombreDep() {
		return this.nombreDep;
	}

	public void setNombreDep(String nombreDep) {
		this.nombreDep = nombreDep;
	}

	public Set getEmpleadoses() {
		return this.empleadoses;
	}

	public void setEmpleadoses(Set empleadoses) {
		this.empleadoses = empleadoses;
	}

}
