package Primero;
// Generated 23-ene-2022 13:04:34 by Hibernate Tools 5.2.3.Final

/**
 * Empleados generated by hbm2java
 */
public class Empleados implements java.io.Serializable {

	private int idEmpleado;
	private Departamentos departamentos;
	private String nombre;
	private String apellidos;
	private String dni;
	private Double salario;

	public Empleados() {
	}

	public Empleados(int idEmpleado, Departamentos departamentos, String dni) {
		this.idEmpleado = idEmpleado;
		this.departamentos = departamentos;
		this.dni = dni;
	}

	public Empleados(int idEmpleado, Departamentos departamentos, String nombre, String apellidos, String dni,
			Double salario) {
		this.idEmpleado = idEmpleado;
		this.departamentos = departamentos;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.dni = dni;
		this.salario = salario;
	}

	public int getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(int idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	public Departamentos getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Departamentos departamentos) {
		this.departamentos = departamentos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Double getSalario() {
		return this.salario;
	}

	public void setSalario(Double salario) {
		this.salario = salario;
	}

}
