spring:
  application:
    name: Mail
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation: TRACE      

