# Configuracion adicional de Spring Boot (opcional)
spring.application.name=Futbol_v2a_DiscoveryService
# Configuracion de Eureka
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# Puerto del servidor
server.port=1111
#Permite conocer los endpoints
#logging.level.org.springframework.web.servlet.mvc.method.annotation=TRACE