#spring.application.name=Futbol_v1
server.port=8080
# Configuracion de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/futbol
spring.datasource.username=root
spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Opcional: Configuracion de Hibernate (JPA)
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#Permite conocer los endpoints
logging.level.org.springframework.web.servlet.mvc.method.annotation=TRACE
spring.jpa.properties.hibernate.format_sql=true

# Poner la ruta personalizado
#springfox.documentation.swagger-ui.base-url=/swagger-ui/

# Habilitar el uso del modelo V3 para la documentacion 
#springfox.documentation.swagger.v2.use-model-v3=true
#spring.mvc.pathmatch.matching-strategy=ant-path-matcher

#springdoc.api-docs.path=/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


